# Generated by Django 5.2.10 on 2026-01-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem_name', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('sage', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.department')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.semester')),
            ],
        ),
    ]
