# Generated by Django 5.2.10 on 2026-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
