# Generated by Django 5.2.10 on 2026-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_facultyid_studentid_student_joined_year_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facultyid',
            name='userid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentid',
            name='userid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyid',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
