# Generated by Django 5.2.10 on 2026-01-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_student_joined_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joined_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
