# Generated by Django 5.2.10 on 2026-01-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_student_joined_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='joined_year',
        ),
    ]
