# Generated by Django 5.2.10 on 2026-01-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_remove_student_joined_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_year',
            field=models.PositiveSmallIntegerField(default=2024),
            preserve_default=False,
        ),
    ]
