# Generated by Django 5.2.10 on 2026-01-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_student_joined_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
