# Generated by Django 5.2.10 on 2026-01-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
