# Generated by Django 5.2.10 on 2026-01-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joined_year',
            field=models.PositiveIntegerField(default=2026, verbose_name='Joined Year'),
        ),
    ]
