# Generated by Django 5.2.10 on 2026-01-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_alter_student_joined_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joined_year',
            field=models.PositiveIntegerField(verbose_name='Joined Year'),
        ),
    ]
