# Generated by Django 5.2.10 on 2026-02-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_facultyid_studentid_student_user_student_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
    ]
