# Generated by Django 5.2.10 on 2026-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_facultyid_studentid_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
