# Generated by Django 5.2.10 on 2026-02-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
