# Generated by Django 5.2.10 on 2026-02-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_remove_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyID',
            fields=[
                ('faculty_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.studentid'),
        ),
    ]
