# Generated by Django 5.2.10 on 2026-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_studentid_id_alter_studentid_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentid',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
