# Generated by Django 5.2.10 on 2026-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyID',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
