# Generated by Django 5.2.10 on 2026-02-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_facultyid_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='studentid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facultyid',
            name='fid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='sid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
