# Generated by Django 5.2.10 on 2026-02-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_facultyid_studentid_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentid',
            name='password',
        ),
    ]
