# Generated by Django 5.2.10 on 2026-02-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_remove_studentid_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
