# Generated by Django 5.2.10 on 2026-02-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_facultyid_id_studentid_id_alter_facultyid_fid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyid',
            old_name='fid',
            new_name='faculty_id',
        ),
        migrations.RenameField(
            model_name='studentid',
            old_name='sid',
            new_name='student_id',
        ),
    ]
