# Generated by Django 5.2.10 on 2026-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_rename_fid_facultyid_faculty_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='facultyid',
        #     name='id',
        # ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='id',
        ),
        migrations.AddField(
            model_name='studentid',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyid',
            name='faculty_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
