# Generated by Django 5.2.10 on 2026-02-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_remove_facultyid_id_remove_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyid',
            name='id',
        ),
    ]
